#!/bin/bash

# Setup to play live-coding in i3wm

# if [ "$#" -eq 0 ]; then
if [ -z "$1" ]; then
    # cd ~/loopier/sketches
    # JAMPATH="jam-$(date +%Y%m%d-%H%M)"
    # mkdir $JAMPATH
    # cd $JAMPATH
    # touch "${JAMPATH}.tidal"
    JAMPATH=~/loopier/jam/jam-boot/
else
    JAMPATH=$1
fi

i3-msg 'workspace 4:Jack' 
cadence &
catia &
cd $JAMPATH
nvim $JAMPATH/*

# i3-msg 'workspace 3:Jam' 
# xfce4-terminal -T "Jam" --hide-menubar -e ~/.local/bin/jamvim &&
# xfce4-terminal -T "Jam" --hide-menubar -e nvim $JAMPATH/* &&
# pwd

